version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/pages/:/usr/share/nginx/html
      - ./nginx/configuration/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s