version: "3.8"

volumes:
  frontend:
  backend:
  nginx:
  

services:
  
  nginx_proxy:
    image: "nginx:alpine"
    volumes: 
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - 3000:80

  db:
    image: "mysql"
    depends_on: 
      - nginx_proxy
    env_file:
      - .env
    networks:
      - common-net

  backend:
    build:
      context: "spring-backend"
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080
    environment:
      - MYSQL_DATABASE=hobbie_db
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=db
    networks:
      - common-net

  frontend:
    build: 
      context: "react-frontend"
      dockerfile: Dockerfile
    depends_on:
      - nginx_proxy
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000
    networks:
      - common-net


networks:
  common-net: