version: "3.8"

volumes:
  nginx:
  

services:
  
  nginx_proxy:
    build:
      context: "nginx"
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    depends_on:
      - frontend
    networks:
      - common-net  

  db:
    image: "mysql"
    networks:
      - common-net
    environment:
      - MYSQL_DATABASE=hobbie_db
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=db  


  backend:
    build:
      context: "spring-backend"
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=hobbie_db
      - MYSQL_PORT=3306
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=db
    networks:
      - common-net
  
  frontend:
    build: 
      context: "react-frontend"
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000
    networks:
      - common-net


networks:
  common-net:
